version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: ./container/backend/Dockerfile
    tty: true
    volumes:
      - ./backend:/api
    ports:
      - "3000:3000"
    DATABASE_HOST: db
    DATABASE_PORT: 3306
    DATABASE_USER: root
    DATABASE_PASSWORD: password
    DATABASE_NAME: database
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: ./container/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3333:3333"
    depends_on:
      - backend

  db:
    build: 
      context: .
      dockerfile: ./container/db/Dockerfile
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database

volumes:
  db-data:
